# kubernetes/secrets.yml
---
apiVersion: v1
kind: Secret
metadata:
  name: laravel-secrets
type: Opaque
data:
  app-key: base64_encoded_app_key_here

---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
type: Opaque
data:
  root-password: base64_encoded_root_password_here
  username: base64_encoded_username_here
  password: base64_encoded_password_here